---

- hosts: ubuntu
  become: yes
  tasks:
  -  name:
     apt:
       upgrade: yes
       update_cache: yes
       cache_valid_time: 86400
  -  name: Install zabbix-agent on Ubuntu
     apt:
       name=zabbix-agent
       state=latest
     notify:
       zabbix-agent systemd
  - name: Configure the zabbix-agent
    replace:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '{{item.regexp}}'
        replace: '{{item.replace}}'
    with_items:
        - {regexp: "^Server=127.0.0.1$", replace: "Server=10.128.0.25"}
        - {regexp: "^ServerActive=127.0.0.1$", replace: "ServerActive=10.128.0.25"}
        - {regexp: "^# Hostname=$", replace: "Hostname={{ ansible_hostname }}"}
  handlers:
  - name: zabbix-agent systemd
    systemd:
     name: zabbix-agent.service
     enabled: yes
     state: started

- hosts: centos
  become: yes
  tasks:
  -  name: Update packages
     yum:
       upgrade: yes
       update_cashe: yes
       cache_valid_time: 86400
  -  name: Install zabbix-agent on Ubuntu
     yum:
       name=zabbix-agent
       state=latest
     notify:
       zabbix-agent systemd
  - name: Configure the zabbix-agent
    replace:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '{{item.regexp}}'
        replace: '{{item.replace}}'
    with_items:
        - {regexp: "^Server=127.0.0.1$", replace: "Server=10.128.0.25"}
        - {regexp: "^ServerActive=127.0.0.1$", replace: "ServerActive=10.128.0.25"}
        - {regexp: "^Hostname=$", replace: "Hostname={{ ansible_hostname }}"}
  handlers:
  - name: zabbix-agent systemd
    systemd:
     name: zabbix-agent.service
     enabled: yes
     state: started
